<?php
declare(strict_types=1)

/**
CREATE TABLE `modell` (
  `mod_id` int NOT NULL AUTO_INCREMENT,
  `mod_mrk_id` int NOT NULL,
  `mod_name` varchar(255) NOT NULL,
  `mod_karosserieform` varchar(20) DEFAULT NULL,
  `mod_baureihe` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`mod_id`),
  INDEX mod_mrk_id_i (mod_mrk_id),
  FOREIGN KEY (mod_mrk_id)
    REFERENCES modell(mrk_id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='CarCost 2.0: Modell';

INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 1, '147', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 1, 'GT', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 2, 'B10', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 3, 'A2', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 3, 'A3', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 3, 'A3', 'Sportback', NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 3, 'A4', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 3, 'A4 Avant', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 3, 'A4', 'Avant', 'B5);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 3, 'A4 Cabrio', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 3, 'A4 S4 Cabrio', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 3, 'A6 Avant', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 3, 'A6 Avant (C4)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 3, 'Avant RS2', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 4, '120d', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 4, '318 ti compact (E46)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 4, '320d (E46)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 4, '320d Touring (E91)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 4, '320i (E46)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 4, '320i Touring (E91)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 4, '325i Touring (E91)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 4, '330d Touring (E91)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 4, '330i Touring (E91)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 4, '525 eta', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 4, '525d (E60/61)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 4, '530d (E39)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 4, '530d GT xDrive (F07)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 4, '530d xDrive (E60)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 4, 'K 100 RS', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 4, 'R 1100 GS', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 4, 'Touring 320d (E46)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 4, 'Z3 Roadster (E36/7)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 5, '300 C', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 5, 'PT Cruiser', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 5, 'Sebring Cabrio', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 5, 'Voyager (ES)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 5, 'Voyager (RG)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 6, 'Berlingo', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 6, 'C1', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 6, 'C2', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 6, 'C3', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 6, 'C4', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 6, 'C4 Picasso', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 6, 'C5 II', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 6, 'C5 III', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 6, 'C5 Kombi II', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 6, 'C5 Limousine/Kombi', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 6, 'C5 Tourer III', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 6, 'C8', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 6, 'Xsara Picasso', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 7, 'Duster', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 7, 'Logan MCV', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 7, 'Sandero', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 8, 'Cuore (L276)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 8, 'Sirion (M1)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 8, 'Sirion (M3)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 9, '500', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 9, 'Barchetta', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 9, 'Bravo', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 9, 'Doblo', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 9, 'Ducato', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 9, 'Multipla', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 9, 'Panda', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 9, 'Punto', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 9, 'Sedici', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 9, 'Stilo Multi Wagon', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 9, 'Ulysse', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 10, 'Fiesta', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 10, 'Focus', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 10, 'Focus C-MAX', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 10, 'Focus Turnier', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 10, 'Fusion', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 10, 'Galaxy', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 10, 'Grand C-MAX', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 10, 'Kuga', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 10, 'Mondeo Limousine', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 10, 'Mondeo Turnier', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 10, 'S-MAX', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 11, 'Accord', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 11, 'Accord Tourer', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 11, 'CB 500', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 11, 'CB125T', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 11, 'Civic', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 11, 'Concerto', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 11, 'CR-V', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 11, 'CR-Z', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 11, 'Jazz', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 11, 'Jazz Hybrid', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 12, 'Getz', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 12, 'i20', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 12, 'i30', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 12, 'ix20', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 13, 'Carens', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 13, 'Carnival', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 13, 'Rio', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 13, 'Sorento', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 14, 'Delta', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 14, 'Kappa', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 14, 'Phedra', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 15, 'Defender 110 Station Wagon', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 16, 'LS400 (UCF20)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 17, '2', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 17, '3', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 17, '323 (BG)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 17, '323 F', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 17, '5', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 17, '6', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 17, '6 Sport Kombi', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 17, 'MPV', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 17, 'MX-6', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 17, 'Premacy', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 18, '190 E', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 18, '260 E (124)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 18, 'A (W168)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 18, 'A (W169)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 18, 'B', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 18, 'B (W246)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 18, 'C (S203) T-Modell', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 18, 'C (W203)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 18, 'E (124) T-Modell', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 18, 'SLK', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 18, 'Vaneo', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 18, 'Vario', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 18, 'C-Klasse (204) T-Modell', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 19, 'Cooper', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 19, 'Cooper Cabrio', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 19, 'Cooper S', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 19, 'One', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 20, 'Colt', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 20, 'Galant Kombi (EAO)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 20, 'Lancer Sportback', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 20, 'Space Star (DG0)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 21, 'Almera Tino', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 21, 'Pathfinder', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 21, 'Primera', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 21, 'Qashqai', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 21, 'Qashqai+2', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 21, 'X-Trail', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 22, 'Agila', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 22, 'Astra F Cabrio', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 22, 'Astra F Caravan', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 22, 'Astra G Cabrio/Coupé', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 22, 'Astra G Cabriolet', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 22, 'Astra G Caravan', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 22, 'Astra G Limousine', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 22, 'Astra G Limousine/Cabrio', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 22, 'Astra G Limousine/Cabrio/Coupé', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 22, 'Astra H Caravan', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 22, 'Astra H Limousine', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 22, 'Combo Tour', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 22, 'Corsa B', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 22, 'Corsa C', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 22, 'Frontera (2-Türer)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 22, 'Frontera (4-Türer)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 22, 'Meriva', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 22, 'Omega A', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 22, 'Omega A Caravan', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 22, 'Omega B', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 22, 'Vectra B', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 22, 'Vectra B Caravan', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 22, 'Vectra C', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 22, 'Vectra C Caravan', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 22, 'Vivaro L1H1', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 22, 'Vivaro L2H1', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 22, 'Zafira A', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 22, 'Zafira B', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 22, 'Zafira OPC', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 23, '1007', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 23, '206', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 23, '206 CC', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 23, '206 SW', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 23, '207', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 23, '207 SW', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 23, '208 GTI', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 23, '307 Break', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 23, '307 Break/SW', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 23, '307 CC', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 23, '307 Limousine', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 23, '307 SW', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 23, '308 Limousine', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 23, '308 SW', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 23, '309 Limousine', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 23, '4007', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 23, '406 Break', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 23, '406 Coup&eacute;', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 23, '406 Limousine', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 23, '406 Limousine/Coup&eacute;', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 23, 'Partner', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 24, '911 Carrera 4 (964)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 24, '968', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 25, 'Clio', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 25, 'Clio Sport', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 25, 'Espace', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 25, 'Grand Scénic', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 25, 'Kangoo', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 25, 'Koleos', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 25, 'Laguna Grandtour', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 25, 'Laguna II', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 25, 'Laguna II Grandtour', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 25, 'Laguna III Coupé', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 25, 'Master Kastenwagen L1H1 2,8t', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 25, 'Megane', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 25, 'Megane Grandtour', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 25, 'Modus', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 25, 'Pay 200 Trafic P', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 25, 'Scénic', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 25, 'Trafic Generation/L2H1', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 25, 'Trafic Generation/Passenger/L1H1', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 25, 'Trafic L1H1', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 25, 'Trafic L2H1', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 25, 'Trafic Passenger/L1H1', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 25, 'Twingo', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 25, 'Twingo II', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 26, '9-3', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 26, '9-3 Aero', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 26, '9-5 Aero Kombi', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 26, '9-5 Kombi', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 27, 'Alhambra', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 27, 'Altea', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 27, 'Altea XL', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 27, 'Ibiza', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 27, 'Ibiza (6J)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 27, 'Leon', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 27, 'Toledo', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 28, 'Fabia', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 28, 'Fabia (5J)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 28, 'Fabia Kombi', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 28, 'Felicia', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 28, 'Octavia', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 28, 'Octavia Combi', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 28, 'Roomster', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 28, 'Superb', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 28, 'Yeti', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 29, 'city cabrio', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 29, 'city-coupé', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 29, 'fortwo cabrio', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 29, 'fortwo coupé', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 30, 'Forester', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 30, 'Impreza', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 31, 'Alto', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 31, 'GSF 400 Bandit', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 31, 'GSF 600 Bandit', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 31, 'Jimny', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 31, 'Splash', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 31, 'SX 4', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 32, 'Avensis', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 32, 'Avensis (T22)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 32, 'Avensis Combi', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 32, 'Avensis Verso', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 32, 'Aygo', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 32, 'Carina', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 32, 'Celica', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 32, 'Corolla', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 32, 'Corolla Combi', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 32, 'Corolla Verso', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 32, 'Prius', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 32, 'RAV4', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 32, 'RAV4 3-Türer', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 32, 'RAV4 5-Türer', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 32, 'Starlet (P6)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 32, 'Starlet (P9)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 32, 'Verso', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 32, 'Yaris', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 33, '1200', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 33, '1302 Cabrio', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 33, 'Caddy Life', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 33, 'Caddy Maxi Life', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 33, 'eco up!', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 33, 'Eos', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 33, 'Fox', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 33, 'Golf I Cabrio', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 33, 'Golf III', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 33, 'Golf III Cabrio', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 33, 'Golf IV', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 33, 'Golf IV Variant', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 33, 'Golf Plus', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 33, 'Golf V', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 33, 'Golf V GTI', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 33, 'Golf VI', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 33, 'Golf VII', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 33, 'Jetta', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 33, 'Lupo', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 33, 'Multivan T5', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 33, 'Passat (35I)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 33, 'Passat (3B)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 33, 'Passat (3BG)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 33, 'Passat Variant (3BG)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 33, 'Passat Variant (3C)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 33, 'Passat Variant (3C5)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 33, 'Polo', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 33, 'Polo (6R1)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 33, 'Polo (86C)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 33, 'Polo (9N)', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 33, 'Sharan', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 33, 'T4', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 33, 'Tiguan', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 33, 'Touran', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 33, 'Transporter T5', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 33, 'up!', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 33, 'Vento', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 34, 'C30', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 34, 'S40', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 34, 'V40', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 34, 'V70', NULL, NULL);

INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 35, 'Otello', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 36, 'ER-6f', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 37, 'FZ6 Fazer', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 37, 'FZS 600 Fazer', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 37, 'XJR 1300', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 37, 'XT 660 Z Tenere', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 37, 'YZF-R6', NULL, NULL);

INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 38, 'Ducato Alkovenwohnmobil Knaus 505L', NULL, NULL);
INSERT INTO `modell` (`mod_id`, `mod_mrk_id`, `mod_name`, `mod_karosserieform`, `mod_baureihe`) VALUES (NULL, 38, 'Ducato Chausson Titanium 718 XLB', NULL, NULL);

*/
